name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython

      - name: Build APK using Docker
        run: |
          sudo docker run --rm -v $GITHUB_WORKSPACE:/home/user/host -w /home/user/host kivy/buildozer buildozer android debug
