name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clean Checkout (with full history)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build APK using Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/host \
            -w /home/user/host \
            kivy/buildozer \
            buildozer android debug
