name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build APK with Docker
        run: |
          sudo docker run --rm \
            -v ${{ github.workspace }}:/home/user/host \
            -w /home/user/host \
            kivy/buildozer \
            buildozer android debug
